// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVAem4qv92HlfFMKr7PpzIan4xw_LKwM',
    appId: '1:1001736280920:web:97d2cbd5af22554240232d',
    messagingSenderId: '1001736280920',
    projectId: 'flutter-signin-57326',
    authDomain: 'flutter-signin-57326.firebaseapp.com',
    storageBucket: 'flutter-signin-57326.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_LWcruTFIE_4qNSzZq8P7HNmGFaAXJQ',
    appId: '1:1001736280920:android:428e6be1ad8d961340232d',
    messagingSenderId: '1001736280920',
    projectId: 'flutter-signin-57326',
    storageBucket: 'flutter-signin-57326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJsGd0CWbZxN50qOHas27XTg2nSSIWOo',
    appId: '1:1001736280920:ios:34675d0a0db009d840232d',
    messagingSenderId: '1001736280920',
    projectId: 'flutter-signin-57326',
    storageBucket: 'flutter-signin-57326.appspot.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJsGd0CWbZxN50qOHas27XTg2nSSIWOo',
    appId: '1:1001736280920:ios:34675d0a0db009d840232d',
    messagingSenderId: '1001736280920',
    projectId: 'flutter-signin-57326',
    storageBucket: 'flutter-signin-57326.appspot.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeVAem4qv92HlfFMKr7PpzIan4xw_LKwM',
    appId: '1:1001736280920:web:f9196e6b0a32a70640232d',
    messagingSenderId: '1001736280920',
    projectId: 'flutter-signin-57326',
    authDomain: 'flutter-signin-57326.firebaseapp.com',
    storageBucket: 'flutter-signin-57326.appspot.com',
  );
}
